version: "2"
services:
  mongo:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"
  loopback:
    build: .
    container_name: "backend"
    links:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"